services:
  - type: web
    name: strategic-impact-analyzer
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: methilashiv@gmail.com
      - key: SMTP_PASS
        value: iejyfbknxjeemfbn
      - key: MAIL_FROM
        value: methilashiv@gmail.com
      - key: PYTHON_VERSION
        value: "3.12.0"
